const RESEND_TOKEN = '1';
const CONFIRM_INFO = '2';
const SUBMIT_LOGIN = '3';
const TIME_EXPIRED = 30;
const SECRET_KEY = 'ZaloMe';

module.exports = {
  RESEND_TOKEN: RESEND_TOKEN,
  CONFIRM_INFO: CONFIRM_INFO,
  SUBMIT_LOGIN: SUBMIT_LOGIN,
  TIME_EXPIRED: TIME_EXPIRED,
  SECRET_KEY: SECRET_KEY,
};
