const RESEND_TOKEN = '1';
const CONFIRM_INFO = '2';
const SUBMIT_LOGIN = '3';
const TIME_EXPIRED = 30;
const SECRET_KEY = 'ZaloMe';
const REQUEST_TIME_EXPIRED = 3000;
const PORT_SERVER = 8085;
const PORT_SOCKET = 8086;

module.exports = {
  RESEND_TOKEN,
  CONFIRM_INFO,
  SUBMIT_LOGIN,
  TIME_EXPIRED,
  SECRET_KEY,
  REQUEST_TIME_EXPIRED,
  PORT_SERVER,
  PORT_SOCKET,
};
